### ISSUE TITLE
admin/usagestats throws "Not a file: undefined" exception

### ISSUE THREAD

**Issue by sfreilich** [ether/pad#169]
Stack trace below.  Wish I could make heads or tails of it:

```
net.appjet.bodylock.JSRuntimeException: Error while executing: Not a file: undefined (module fileutils.js#31)
at net.appjet.bodylock.InnerExecutable.execute(bodylock.scala:84)
at net.appjet.oui.execution$$anonfun$execute$4.apply(execution.scala:508)
at net.appjet.oui.NoninheritedDynamicVariable.withValue(dynamicvar.scala:38)
at net.appjet.oui.ExecutionContextUtils$.withContext(execution.scala:334)
at net.appjet.oui.execution$.execute(execution.scala:504)
at net.appjet.oui.execution$.execute(execution.scala:483)
at net.appjet.oui.OuiServlet.execute(execution.scala:413)
at net.appjet.oui.OuiServlet.doGet(execution.scala:360)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:502)
at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
at org.mortbay.jetty.handler.HandlerList.handle(HandlerList.java:49)
at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
at org.mortbay.jetty.Server.handle(Server.java:326)
at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:536)
at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:913)
at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:539)
at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:405)
at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
 Caused by: org.mozilla.javascript.JavaScriptException: Not a file: undefined (module fileutils.js#31)
at JS$module$fileutils$js$24._c1(module fileutils.js:31)
at JS$module$fileutils$js$24.call(module fileutils.js)
at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
at JS$module$fileutils$js$24._c2(module fileutils.js:37)
at JS$module$fileutils$js$24.call(module fileutils.js)
at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
at JS$module$etherpad$utils$js$30._c10(module etherpad/utils.js:132)
at JS$module$etherpad$utils$js$30.call(module etherpad/utils.js)
at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
at JS$module$etherpad$utils$js$30._c12(module etherpad/utils.js:151)
at JS$module$etherpad$utils$js$30.call(module etherpad/utils.js)
at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
at JS$module$etherpad$control$statscontrol$js$86._c80(module etherpad/control/statscontrol.js:723)
at JS$module$etherpad$control$statscontrol$js$86.call(module etherpad/control/statscontrol.js)
at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:57)
at JS$module$dispatch$js$9._c11(module dispatch.js:136)
at JS$module$dispatch$js$9.call(module dispatch.js)
at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2348)
at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:272)
at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:127)
at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)
at JS$module$dispatch$js$9._c9(module dispatch.js:96)
at JS$module$dispatch$js$9.call(module dispatch.js)
at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:119)
at JS$module$etherpad$control$admincontrol$js$78._c2(module etherpad/control/admincontrol.js:114)
at JS$module$etherpad$control$admincontrol$js$78.call(module etherpad/control/admincontrol.js)
at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
at JS$module$dispatch$js$9._c11(module dispatch.js:123)
at JS$module$dispatch$js$9.call(module dispatch.js)
at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2348)
at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:272)
at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:127)
at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)
at JS$module$dispatch$js$9._c9(module dispatch.js:96)
at JS$module$dispatch$js$9.call(module dispatch.js)
at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:119)
at JS$module$main$js$8._c24(module main.js:427)
at JS$module$main$js$8.call(module main.js)
at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:108)
at JS$module$main$js$8._c5(module main.js:125)
at JS$module$main$js$8.call(module main.js)
at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:119)
at JS$module$onrequest$js$195._c0(module onrequest.js:24)
at JS$module$onrequest$js$195.call(module onrequest.js)
at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:401)
at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3004)
at JS$module$onrequest$js$195.call(module onrequest.js)
at JS$module$onrequest$js$195.exec(module onrequest.js)
at net.appjet.bodylock.InnerExecutable$$anonfun$execute$1.apply(bodylock.scala:76)
at net.appjet.bodylock.InnerExecutable$$anonfun$execute$1.apply(bodylock.scala:75)
at net.appjet.bodylock.BodyLock$.runInContext(bodylock.scala:111)
at net.appjet.bodylock.InnerExecutable.execute(bodylock.scala:75)
... 23 more
```

**Comment by sesam** [comment]
I beleive this is fixed (the missing files that were re-added in the end of last year...). Will reopen otherwise. ktnxbai
