### ISSUE TITLE
admin/dashboard intermittently results in StackOverflowError

### ISSUE THREAD

**Issue by sfreilich** [ether/pad#170]
Stack trace:

```
net.appjet.bodylock.JSRuntimeException: Error while executing: null
at net.appjet.bodylock.InnerExecutable.execute(bodylock.scala:84)
at net.appjet.oui.execution$$anonfun$execute$4.apply(execution.scala:508)
at net.appjet.oui.NoninheritedDynamicVariable.withValue(dynamicvar.scala:38)
at net.appjet.oui.ExecutionContextUtils$.withContext(execution.scala:334)
at net.appjet.oui.execution$.execute(execution.scala:504)
at net.appjet.oui.execution$.execute(execution.scala:483)
at net.appjet.oui.OuiServlet.execute(execution.scala:413)
at net.appjet.oui.OuiServlet.doGet(execution.scala:360)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:502)
at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
at org.mortbay.jetty.handler.HandlerList.handle(HandlerList.java:49)
at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
at org.mortbay.jetty.Server.handle(Server.java:326)
at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:536)
at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:913)
at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:539)
at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:405)
at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
Caused by: java.lang.StackOverflowError
at scala.runtime.BoxedArray$AnyIterator.next(BoxedArray.scala:48)
at scala.Iterator$class.fold$1(Iterator.scala:533)
at scala.Iterator$class.fold$1(Iterator.scala:533)
at scala.Iterator$class.fold$1(Iterator.scala:533)
    [... and so on ...]
```

Presumably, this happens when the list in question is too long, since fold is foolishly using tail-recursion which isn't compiled out.  Don't know why this only happens some times and not other times.  Sometimes happens when the server is restarted, sometimes not.  Dashboard bins things based on time, is the bug time-dependent?

**Comment by sesam** [comment]
This is probably happening intermittently while the dashboard is still busy collecting data. The error may stay until the first pad visitor has been logged such that there are some statistics available to show.
