### ISSUE TITLE
Export error: URL seems to be an unsupported one.

### ISSUE THREAD

**Issue by etimau** [ether/pad#217]
Hi,

I've just installed etherpad v1.1 on my Debian server.
Everything is ok except the export feature (and import, but I think it is the same problem).
When I try to export a pad to PDF for example, I get an error:
Error: An unknown failure occurred. (#3)

Looking at the logs, I see this exception:
com.sun.star.lang.IllegalArgumentException: URL seems to be an unsupported one.
        at com.sun.star.lib.uno.environments.remote.Job.remoteUnoRequestRaisedException(Job.java:180)
        at com.sun.star.lib.uno.environments.remote.Job.execute(Job.java:146)
        at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:338)
        at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:307)
        at com.sun.star.lib.uno.environments.remote.JavaThreadPool.enter(JavaThreadPool.java:94)
        at com.sun.star.lib.uno.bridges.java_remote.java_remote_bridge.sendRequest(java_remote_bridge.java:642)
        at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.request(ProxyFactory.java:154)
        at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.invoke(ProxyFactory.java:136)
        at $Proxy7.loadComponentFromURL(Unknown Source)
        at com.etherpad.openofficeservice.OpenOfficeFileConverter.convertFile(importexport.scala:100)
        at com.etherpad.openofficeservice.OpenOfficeService$.convertFile(importexport.scala:194)
        at com.etherpad.openofficeservice.OpenOfficeService.convertFile(importexport.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:160)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:243)
        at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:86)
        at JS$module$etherpad$importexport$importexport$js$137._c9(module etherpad/importexport/importexport.js:148)
        at JS$module$etherpad$importexport$importexport$js$137.call(module etherpad/importexport/importexport.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
        at JS$module$etherpad$importexport$importexport$js$137._c7(module etherpad/importexport/importexport.js:88)
        at JS$module$etherpad$importexport$importexport$js$137.call(module etherpad/importexport/importexport.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:86)
        at JS$module$main$js$8._c12(module main.js:165)
        at JS$module$main$js$8.call(module main.js)
        at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2348)
        at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:272)
        at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:127)
        at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)
        at JS$module$onscheduledtask$js$172._c1(module onscheduledtask.js:32)
        at JS$module$onscheduledtask$js$172.call(module onscheduledtask.js)
        at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:57)
        at JS$module$onscheduledtask$js$172._c0(module onscheduledtask.js:17)
        at JS$module$onscheduledtask$js$172.call(module onscheduledtask.js)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:401)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3004)
        at JS$module$onscheduledtask$js$172.call(module onscheduledtask.js)
        at JS$module$onscheduledtask$js$172.exec(module onscheduledtask.js)
        at net.appjet.bodylock.InnerExecutable$$anonfun$execute$1.apply(bodylock.scala:76)
        at net.appjet.bodylock.InnerExecutable$$anonfun$execute$1.apply(bodylock.scala:75)
        at net.appjet.bodylock.BodyLock$.runInContext(bodylock.scala:111)
        at net.appjet.bodylock.InnerExecutable.execute(bodylock.scala:75)
        at net.appjet.oui.execution$$anonfun$execute$4.apply(execution.scala:508)
        at net.appjet.oui.NoninheritedDynamicVariable.withValue(dynamicvar.scala:38)
        at net.appjet.oui.ExecutionContextUtils$.withContext(execution.scala:334)
        at net.appjet.oui.execution$.execute(execution.scala:504)
        at net.appjet.oui.execution$.runOutOfBand(execution.scala:631)
        at net.appjet.ajstdlib.execution$.runTask(ajstdlib.scala:140)
        at net.appjet.ajstdlib.execution$TaskRunner.call(ajstdlib.scala:177)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
        at java.util.concurrent.FutureTask.run(FutureTask.java:138)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:207)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
        at java.lang.Thread.run(Thread.java:619)
com.etherpad.openofficeservice.OOSException: Unknown exception occurred: URL seems to be an unsupported one.
        at com.etherpad.openofficeservice.OpenOfficeFileConverter.convertFile(importexport.scala:122)
        at com.etherpad.openofficeservice.OpenOfficeService$.convertFile(importexport.scala:194)
        at com.etherpad.openofficeservice.OpenOfficeService.convertFile(importexport.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:160)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:243)
        at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:86)
        at JS$module$etherpad$importexport$importexport$js$137._c9(module etherpad/importexport/importexport.js:148)
        at JS$module$etherpad$importexport$importexport$js$137.call(module etherpad/importexport/importexport.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
        at JS$module$etherpad$importexport$importexport$js$137._c7(module etherpad/importexport/importexport.js:88)
        at JS$module$etherpad$importexport$importexport$js$137.call(module etherpad/importexport/importexport.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:86)
        at JS$module$main$js$8._c12(module main.js:165)
        at JS$module$main$js$8.call(module main.js)
        at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2348)
        at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:272)
        at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:127)
        at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)
        at JS$module$onscheduledtask$js$172._c1(module onscheduledtask.js:32)
        at JS$module$onscheduledtask$js$172.call(module onscheduledtask.js)
        at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:57)
        at JS$module$onscheduledtask$js$172._c0(module onscheduledtask.js:17)
        at JS$module$onscheduledtask$js$172.call(module onscheduledtask.js)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:401)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3004)
        at JS$module$onscheduledtask$js$172.call(module onscheduledtask.js)
        at JS$module$onscheduledtask$js$172.exec(module onscheduledtask.js)
        at net.appjet.bodylock.InnerExecutable$$anonfun$execute$1.apply(bodylock.scala:76)
        at net.appjet.bodylock.InnerExecutable$$anonfun$execute$1.apply(bodylock.scala:75)
        at net.appjet.bodylock.BodyLock$.runInContext(bodylock.scala:111)
        at net.appjet.bodylock.InnerExecutable.execute(bodylock.scala:75)
        at net.appjet.oui.execution$$anonfun$execute$4.apply(execution.scala:508)
        at net.appjet.oui.NoninheritedDynamicVariable.withValue(dynamicvar.scala:38)
        at net.appjet.oui.ExecutionContextUtils$.withContext(execution.scala:334)
        at net.appjet.oui.execution$.execute(execution.scala:504)
        at net.appjet.oui.execution$.runOutOfBand(execution.scala:631)
        at net.appjet.ajstdlib.execution$.runTask(ajstdlib.scala:140)
        at net.appjet.ajstdlib.execution$TaskRunner.call(ajstdlib.scala:177)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
        at java.util.concurrent.FutureTask.run(FutureTask.java:138)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:207)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
        at java.lang.Thread.run(Thread.java:619)
- I've checked my open office installation and it seems to be ok.
- The soffice server is running and listening on port 8100.
- I don't see any warnings when etherpad starts.
- In /tmp, I see the pad content to be converted (ooconvert-6561474244597942026.html for example) and an empty pdf is created (ooconvert-6314163518182802334.pdf for example).

How can I make the export function work?
Thanks for your help.

Etienne.

**Comment by Zir0h** [comment]
Did you add etherpad.soffice = /usr/bin/soffice to your config file?

**Comment by etimau** [comment]
I did not have to add it, it was there...
(In /etc/etherpad/etherpad.local.properties)

**Comment by LarsFronius** [comment]
Hi, 
I get exactly the same error under a Red Hat 5.5 Linux. 
The etherpad.soffice path is set and soffice is up and listening on port 8100.
Did also try with a new build from the master branch. Same error.

**Comment by LarsFronius** [comment]
Here is some more information:
Etherpad 1.1-45-g15f8474
OpenOffice.org 3.1  310m19(Build:9420)
Started as /usr/bin/soffice -nologo -nofirststartwizard -headless -norestore -invisible -"accept=socket,host=localhost,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager"
It starts and opens a socket:
fuser -n tcp 8100
8100/tcp:            32468

Error when trying to convert:

com.sun.star.lang.IllegalArgumentException: URL seems to be an unsupported one.
    at com.sun.star.lib.uno.environments.remote.Job.remoteUnoRequestRaisedException(Job.java:180)
    at com.sun.star.lib.uno.environments.remote.Job.execute(Job.java:146)
    at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:338)
    at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:307)
    at com.sun.star.lib.uno.environments.remote.JavaThreadPool.enter(JavaThreadPool.java:94)
    at com.sun.star.lib.uno.bridges.java_remote.java_remote_bridge.sendRequest(java_remote_bridge.java:642)
    at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.request(ProxyFactory.java:154)
    at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.invoke(ProxyFactory.java:136)
    at $Proxy7.loadComponentFromURL(Unknown Source)
    at com.etherpad.openofficeservice.OpenOfficeFileConverter.convertFile(importexport.scala:100)
    at com.etherpad.openofficeservice.OpenOfficeService$.convertFile(importexport.scala:194)
    at com.etherpad.openofficeservice.OpenOfficeService.convertFile(importexport.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:160)
    at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:243)
    at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:86)
    at JS$module$etherpad$importexport$importexport$js$137._c9(module etherpad/importexport/importexport.js:148)
    at JS$module$etherpad$importexport$importexport$js$137.call(module etherpad/importexport/importexport.js)
    at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
    at JS$module$etherpad$importexport$importexport$js$137._c7(module etherpad/importexport/importexport.js:88)
    at JS$module$etherpad$importexport$importexport$js$137.call(module etherpad/importexport/importexport.js)
    at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:86)
    at JS$module$main$js$8._c12(module main.js:165)
    at JS$module$main$js$8.call(module main.js)
    at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2348)
    at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:272)
    at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:127)
    at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)
    at JS$module$onscheduledtask$js$172._c1(module onscheduledtask.js:32)
    at JS$module$onscheduledtask$js$172.call(module onscheduledtask.js)
    at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:57)
    at JS$module$onscheduledtask$js$172._c0(module onscheduledtask.js:17)
    at JS$module$onscheduledtask$js$172.call(module onscheduledtask.js)
    at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:401)
    at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3004)
    at JS$module$onscheduledtask$js$172.call(module onscheduledtask.js)
    at JS$module$onscheduledtask$js$172.exec(module onscheduledtask.js)
    at net.appjet.bodylock.InnerExecutable$$anonfun$execute$1.apply(bodylock.scala:76)
    at net.appjet.bodylock.InnerExecutable$$anonfun$execute$1.apply(bodylock.scala:75)
    at net.appjet.bodylock.BodyLock$.runInContext(bodylock.scala:111)
    at net.appjet.bodylock.InnerExecutable.execute(bodylock.scala:75)
    at net.appjet.oui.execution$$anonfun$execute$4.apply(execution.scala:508)
    at net.appjet.oui.NoninheritedDynamicVariable.withValue(dynamicvar.scala:38)
    at net.appjet.oui.ExecutionContextUtils$.withContext(execution.scala:334)
    at net.appjet.oui.execution$.execute(execution.scala:504)
    at net.appjet.oui.execution$.runOutOfBand(execution.scala:631)
    at net.appjet.ajstdlib.execution$.runTask(ajstdlib.scala:140)
    at net.appjet.ajstdlib.execution$TaskRunner.call(ajstdlib.scala:177)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
com.etherpad.openofficeservice.OOSException: Unknown exception occurred: URL seems to be an unsupported one.
    at com.etherpad.openofficeservice.OpenOfficeFileConverter.convertFile(importexport.scala:122)
    at com.etherpad.openofficeservice.OpenOfficeService$.convertFile(importexport.scala:194)
    at com.etherpad.openofficeservice.OpenOfficeService.convertFile(importexport.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:160)
    at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:243)
    at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:86)
    at JS$module$etherpad$importexport$importexport$js$137._c9(module etherpad/importexport/importexport.js:148)
    at JS$module$etherpad$importexport$importexport$js$137.call(module etherpad/importexport/importexport.js)
    at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
    at JS$module$etherpad$importexport$importexport$js$137._c7(module etherpad/importexport/importexport.js:88)
    at JS$module$etherpad$importexport$importexport$js$137.call(module etherpad/importexport/importexport.js)
    at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:86)
    at JS$module$main$js$8._c12(module main.js:165)
    at JS$module$main$js$8.call(module main.js)
    at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2348)
    at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:272)
    at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:127)
    at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)
    at JS$module$onscheduledtask$js$172._c1(module onscheduledtask.js:32)
    at JS$module$onscheduledtask$js$172.call(module onscheduledtask.js)
    at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:57)
    at JS$module$onscheduledtask$js$172._c0(module onscheduledtask.js:17)
    at JS$module$onscheduledtask$js$172.call(module onscheduledtask.js)
    at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:401)
    at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3004)
    at JS$module$onscheduledtask$js$172.call(module onscheduledtask.js)
    at JS$module$onscheduledtask$js$172.exec(module onscheduledtask.js)
    at net.appjet.bodylock.InnerExecutable$$anonfun$execute$1.apply(bodylock.scala:76)
    at net.appjet.bodylock.InnerExecutable$$anonfun$execute$1.apply(bodylock.scala:75)
    at net.appjet.bodylock.BodyLock$.runInContext(bodylock.scala:111)
    at net.appjet.bodylock.InnerExecutable.execute(bodylock.scala:75)
    at net.appjet.oui.execution$$anonfun$execute$4.apply(execution.scala:508)
    at net.appjet.oui.NoninheritedDynamicVariable.withValue(dynamicvar.scala:38)
    at net.appjet.oui.ExecutionContextUtils$.withContext(execution.scala:334)
    at net.appjet.oui.execution$.execute(execution.scala:504)
    at net.appjet.oui.execution$.runOutOfBand(execution.scala:631)
    at net.appjet.ajstdlib.execution$.runTask(ajstdlib.scala:140)
    at net.appjet.ajstdlib.execution$TaskRunner.call(ajstdlib.scala:177)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)

This is what stands in the etherpad config
etherpad.soffice = /usr/bin/soffice

**Comment by LarsFronius** [comment]
Hi, I figured it out!
I came across this entry in the OOo-board: http://www.oooforum.org/forum/viewtopic.phtml?p=333491&highlight=url+seems+unsupported+one#333491
Seems like a bug in 3.1. 
I installed the 3.2.0 RPMs from OOo-Website manually and now I can import and export nicely. :)

**Comment by devBioS** [comment]
Hi!

Myinstallation alreads had OOo 3.2.1 installed and it didn't work.
There are just some openoffice deb packages missing, after issuing:

$ sudo apt-get install openoffice.org-writer openoffice.org-impress

and restarting the soffice daemon every export AND import worked immediately fine :)
Reference: http://www.johnyerhot.com/2010/10/30/unoconv-url-seems-to-be-an-unsupported-one/
