### ISSUE TITLE
"body" ReferenceError in the admin console

### ISSUE THREAD

**Issue by xkahn** [ether/pad#222]
While trying to inspect a pad in the admin interface, a stack
trace would be displayed instead.
Fixes: Error while executing: ReferenceError: "body" is not defined.
(module etherpad/control/admincontrol.js#531)

Stack trace:
        at net.appjet.bodylock.InnerExecutable.execute(bodylock.scala:84)
        at net.appjet.oui.execution$$anonfun$execute$4.apply(execution.scala:508)
        at net.appjet.oui.NoninheritedDynamicVariable.withValue(dynamicvar.scala:38)
        at net.appjet.oui.ExecutionContextUtils$.withContext(execution.scala:334)
        at net.appjet.oui.execution$.execute(execution.scala:504)
        at net.appjet.oui.execution$.execute(execution.scala:483)
        at net.appjet.oui.OuiServlet.execute(execution.scala:413)
        at net.appjet.oui.OuiServlet.doGet(execution.scala:360)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:502)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.handler.HandlerList.handle(HandlerList.java:49)
        at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:536)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:913)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:539)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:405)
        at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
        at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
    Caused by: org.mozilla.javascript.EcmaError: ReferenceError: "body" is not defined. (module etherpad/control/admincontrol.js#531)
        at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3559)
        at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3537)
        at org.mozilla.javascript.ScriptRuntime.notFoundError(ScriptRuntime.java:3622)
        at org.mozilla.javascript.ScriptRuntime.nameOrFunction(ScriptRuntime.java:1718)
        at org.mozilla.javascript.ScriptRuntime.name(ScriptRuntime.java:1657)
        at JS$module$etherpad$control$admincontrol$js$78._c34(module etherpad/control/admincontrol.js:531)
        at JS$module$etherpad$control$admincontrol$js$78.call(module etherpad/control/admincontrol.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
        at JS$module$etherpad$pad$model$js$37._c7(module etherpad/pad/model.js:459)
        at JS$module$etherpad$pad$model$js$37.call(module etherpad/pad/model.js)
        at org.mozilla.javascript.JavaAdapter.doCall(JavaAdapter.java:568)
        at org.mozilla.javascript.JavaAdapter.callMethod(JavaAdapter.java:543)
        at adapter2.apply(<adapter>)
        at net.appjet.ajstdlib.SQLBase$$anonfun$inTransaction$1$$anonfun$apply$1.apply(sqlbase.scala:114)
        at net.appjet.oui.NoninheritedDynamicVariable.withValue(dynamicvar.scala:38)
        at net.appjet.ajstdlib.SQLBase$$anonfun$inTransaction$1.apply(sqlbase.scala:109)
        at net.appjet.ajstdlib.SQLBase$$anonfun$inTransaction$1.apply(sqlbase.scala:105)
        at net.appjet.ajstdlib.SQLBase$$anonfun$withConnection$1.apply(sqlbase.scala:93)
        at net.appjet.oui.NoninheritedDynamicVariable.withValue(dynamicvar.scala:38)
        at net.appjet.ajstdlib.SQLBase.withConnection(sqlbase.scala:92)
        at net.appjet.ajstdlib.SQLBase.inTransaction(sqlbase.scala:105)
        at sun.reflect.GeneratedMethodAccessor106.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:160)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:243)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
        at JS$module$sqlbase$sqlcommon$js$16._c6(module sqlbase/sqlcommon.js:64)
        at JS$module$sqlbase$sqlcommon$js$16.call(module sqlbase/sqlcommon.js)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
        at JS$module$etherpad$pad$model$js$37._c6(module etherpad/pad/model.js:107)
        at JS$module$etherpad$pad$model$js$37.call(module etherpad/pad/model.js)
        at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:57)
        at JS$module$sync$js$15._c7(module sync.js:75)
        at JS$module$sync$js$15.call(module sync.js)
        at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)
        at JS$module$etherpad$pad$model$js$37._c47(module etherpad/pad/model.js:483)
        at JS$module$etherpad$pad$model$js$37.call(module etherpad/pad/model.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
        at JS$module$etherpad$pad$model$js$37._c5(module etherpad/pad/model.js:106)
        at JS$module$etherpad$pad$model$js$37.call(module etherpad/pad/model.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:86)
        at JS$module$etherpad$control$admincontrol$js$78._c30(module etherpad/control/admincontrol.js:474)
        at JS$module$etherpad$control$admincontrol$js$78.call(module etherpad/control/admincontrol.js)
        at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:57)
        at JS$module$dispatch$js$9._c11(module dispatch.js:139)
        at JS$module$dispatch$js$9.call(module dispatch.js)
        at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2348)
        at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:272)
        at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:127)
        at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)
        at JS$module$dispatch$js$9._c9(module dispatch.js:96)
        at JS$module$dispatch$js$9.call(module dispatch.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:119)
        at JS$module$main$js$8._c24(module main.js:423)
        at JS$module$main$js$8.call(module main.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:108)
        at JS$module$main$js$8._c5(module main.js:123)
        at JS$module$main$js$8.call(module main.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:119)
        at JS$module$onrequest$js$236._c0(module onrequest.js:24)
        at JS$module$onrequest$js$236.call(module onrequest.js)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:401)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3004)
        at JS$module$onrequest$js$236.call(module onrequest.js)
        at JS$module$onrequest$js$236.exec(module onrequest.js)
        at net.appjet.bodylock.InnerExecutable$$anonfun$execute$1.apply(bodylock.scala:76)
        at net.appjet.bodylock.InnerExecutable$$anonfun$execute$1.apply(bodylock.scala:75)
        at net.appjet.bodylock.BodyLock$.runInContext(bodylock.scala:111)
        at net.appjet.bodylock.InnerExecutable.execute(bodylock.scala:75)
        ... 23 more

**Comment by xkahn** [comment]
Potential fix at: https://github.com/ether/pad/pull/225

**Comment by xkahn** [comment]
This patch has been accepted: 
<etherbot> pad: master Benjamin Kahn \* b716b1c (1 files in 1 dirs): 
  Fix "body" ReferenceError in the admin console ...
<etherbot> pad: master Benjamin Kahn \* 943523f (1 files in 1 dirs): 
  Fix admin pad snoop on non-pro pads ...
<etherbot> pad: master Benjamin Kahn \* 6ca74a5 (1 files in 1 dirs): 
  Fix display of pad names in the twitterStyleTags plugin ...
<etherbot> pad: master commits 15f8474...6ca74a5 - http://bit.ly/g2gkbh
