### ISSUE TITLE
admin pad snoop on non-pro pads throws domainId exception

### ISSUE THREAD

**Issue by xkahn** [ether/pad#223]
When trying to snoop a non-pro pad as an admin, you see the following problem:

net.appjet.bodylock.JSRuntimeException: Error: Error getting request domain id.
        at net.appjet.bodylock.BodyLock$.unwrapExceptionIfNecessary(bodylock.scala:160)
        at net.appjet.bodylock.InnerExecutable.execute(bodylock.scala:80)
        at net.appjet.oui.execution$$anonfun$execute$4.apply(execution.scala:508)
        at net.appjet.oui.NoninheritedDynamicVariable.withValue(dynamicvar.scala:38)
        at net.appjet.oui.ExecutionContextUtils$.withContext(execution.scala:334)
        at net.appjet.oui.execution$.execute(execution.scala:504)
        at net.appjet.oui.execution$.execute(execution.scala:483)
        at net.appjet.oui.OuiServlet.execute(execution.scala:413)
        at net.appjet.oui.OuiServlet.doGet(execution.scala:360)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:502)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.handler.HandlerList.handle(HandlerList.java:49)
        at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:536)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:913)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:539)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:405)
        at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
        at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
    Caused by: org.mozilla.javascript.JavaScriptException: Error: Error getting request domain id. (module etherpad/pro/domains.js#136)
        at JS$module$etherpad$pro$domains$js$49._c11(module etherpad/pro/domains.js:136)
        at JS$module$etherpad$pro$domains$js$49.call(module etherpad/pro/domains.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:119)
        at JS$module$etherpad$pro$pro$accounts$js$50._c46(module etherpad/pro/pro_accounts.js:563)
        at JS$module$etherpad$pro$pro$accounts$js$50.call(module etherpad/pro/pro_accounts.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:108)
        at JS$module$etherpad$pro$pro$accounts$js$50._c21(module etherpad/pro/pro_accounts.js:247)
        at JS$module$etherpad$pro$pro$accounts$js$50.call(module etherpad/pro/pro_accounts.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:108)
        at JS$module$etherpad$pro$pro$accounts$js$50._c22(module etherpad/pro/pro_accounts.js:261)
        at JS$module$etherpad$pro$pro$accounts$js$50.call(module etherpad/pro/pro_accounts.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:119)
        at JS$module$etherpad$pad$padusers$js$58._c5(module etherpad/pad/padusers.js:73)
        at JS$module$etherpad$pad$padusers$js$58.call(module etherpad/pad/padusers.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:119)
        at JS$module$etherpad$control$pad$pad$control$js$146._c18(module etherpad/control/pad/pad_control.js:295)
        at JS$module$etherpad$control$pad$pad$control$js$146.call(module etherpad/control/pad/pad_control.js)
        at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2348)
        at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:272)
        at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:127)
        at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)
        at JS$module$dispatch$js$9._c9(module dispatch.js:96)
        at JS$module$dispatch$js$9.call(module dispatch.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:119)
        at JS$module$main$js$8._c24(module main.js:412)
        at JS$module$main$js$8.call(module main.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:108)
        at JS$module$main$js$8._c5(module main.js:123)
        at JS$module$main$js$8.call(module main.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:119)
        at JS$module$onrequest$js$236._c0(module onrequest.js:24)
        at JS$module$onrequest$js$236.call(module onrequest.js)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:401)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3004)
        at JS$module$onrequest$js$236.call(module onrequest.js)
        at JS$module$onrequest$js$236.exec(module onrequest.js)
        at net.appjet.bodylock.InnerExecutable$$anonfun$execute$1.apply(bodylock.scala:76)
        at net.appjet.bodylock.InnerExecutable$$anonfun$execute$1.apply(bodylock.scala:75)
        at net.appjet.bodylock.BodyLock$.runInContext(bodylock.scala:111)
        at net.appjet.bodylock.InnerExecutable.execute(bodylock.scala:75)
        ... 23 more

**Comment by xkahn** [comment]
Potential fix at: https://github.com/ether/pad/pull/225

**Comment by xkahn** [comment]
This patch has been accepted: 
<etherbot> pad: master Benjamin Kahn \* b716b1c (1 files in 1 dirs): 
  Fix "body" ReferenceError in the admin console ...
<etherbot> pad: master Benjamin Kahn \* 943523f (1 files in 1 dirs): 
  Fix admin pad snoop on non-pro pads ...
<etherbot> pad: master Benjamin Kahn \* 6ca74a5 (1 files in 1 dirs): 
  Fix display of pad names in the twitterStyleTags plugin ...
<etherbot> pad: master commits 15f8474...6ca74a5 - http://bit.ly/g2gkbh
