### ISSUE TITLE
The debian-supplied build is in trouble (installing plugins causes error, tedious workaround=reinstall)

### ISSUE THREAD

**Issue by zeigerpuppy** [ether/pad#234]
Etherpad was installed from apt.
After installing some plugins etherpad fails.

I tried uninstalling the plugin using this link:
http://fqdn.org:9000/ep/admin/pluginmanager/?plugin=showImages&action=uninstall
## but the error does not go away, is there a way to manually disable the plugin?

You like apples? An error occurred in the error handler while handling an error. How do you like them apples?
net.appjet.bodylock.JSRuntimeException: Error: yuicompressor.compressJS error: 1:7:syntax error
at net.appjet.bodylock.BodyLock$.unwrapExceptionIfNecessary(bodylock.scala:160)
at net.appjet.bodylock.InnerExecutable.execute(bodylock.scala:80)
at net.appjet.oui.execution$$anonfun$execute$4.apply(execution.scala:517)
at net.appjet.oui.NoninheritedDynamicVariable.withValue(dynamicvar.scala:38)
at net.appjet.oui.ExecutionContextUtils$.withContext(execution.scala:334)
at net.appjet.oui.execution$.execute(execution.scala:504)
at net.appjet.oui.execution$.execute(execution.scala:483)
at net.appjet.oui.OuiServlet.execute(execution.scala:413)
at net.appjet.oui.OuiServlet.doGet(execution.scala:360)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:502)
at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
at org.mortbay.jetty.handler.HandlerList.handle(HandlerList.java:49)
at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
at org.mortbay.jetty.Server.handle(Server.java:326)
at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:536)
at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:913)
at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:539)
at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:405)
at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
Caused by: org.mozilla.javascript.JavaScriptException: [object Error](module yuicompressor.js#55)
at JS$module$yuicompressor$js$25._c6(module yuicompressor.js:55)
at JS$module$yuicompressor$js$25.call(module yuicompressor.js)
at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
at JS$module$yuicompressor$js$25._c4(module yuicompressor.js:45)
at JS$module$yuicompressor$js$25.call(module yuicompressor.js)
at org.mozilla.javascript.JavaAdapter.doCall(JavaAdapter.java:568)
at org.mozilla.javascript.JavaAdapter.callMethod(JavaAdapter.java:543)
at adapter5.error()
at yuicompressor.org.mozilla.javascript.Parser.addError(Parser.java:140)
at yuicompressor.org.mozilla.javascript.Parser.reportError(Parser.java:154)
at yuicompressor.org.mozilla.javascript.Parser.primaryExpr(Parser.java:2132)
at yuicompressor.org.mozilla.javascript.Parser.memberExpr(Parser.java:1740)
at yuicompressor.org.mozilla.javascript.Parser.unaryExpr(Parser.java:1601)
at yuicompressor.org.mozilla.javascript.Parser.mulExpr(Parser.java:1530)
at yuicompressor.org.mozilla.javascript.Parser.addExpr(Parser.java:1511)
at yuicompressor.org.mozilla.javascript.Parser.shiftExpr(Parser.java:1491)
at yuicompressor.org.mozilla.javascript.Parser.relExpr(Parser.java:1465)
at yuicompressor.org.mozilla.javascript.Parser.eqExpr(Parser.java:1421)
at yuicompressor.org.mozilla.javascript.Parser.bitAndExpr(Parser.java:1410)
at yuicompressor.org.mozilla.javascript.Parser.bitXorExpr(Parser.java:1399)
at yuicompressor.org.mozilla.javascript.Parser.bitOrExpr(Parser.java:1388)
at yuicompressor.org.mozilla.javascript.Parser.andExpr(Parser.java:1376)
at yuicompressor.org.mozilla.javascript.Parser.orExpr(Parser.java:1364)
at yuicompressor.org.mozilla.javascript.Parser.condExpr(Parser.java:1347)
at yuicompressor.org.mozilla.javascript.Parser.assignExpr(Parser.java:1332)
at yuicompressor.org.mozilla.javascript.Parser.expr(Parser.java:1319)
at yuicompressor.org.mozilla.javascript.Parser.statementHelper(Parser.java:1216)
at yuicompressor.org.mozilla.javascript.Parser.statement(Parser.java:666)
at yuicompressor.org.mozilla.javascript.Parser.parse(Parser.java:388)
at yuicompressor.org.mozilla.javascript.Parser.parse(Parser.java:347)
at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:312)
at com.yahoo.platform.yui.compressor.JavaScriptCompressor.(JavaScriptCompressor.java:535)
at sun.reflect.GeneratedConstructorAccessor19.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
at org.mozilla.javascript.MemberBox.newInstance(MemberBox.java:184)
at org.mozilla.javascript.NativeJavaClass.constructSpecific(NativeJavaClass.java:274)
at org.mozilla.javascript.NativeJavaClass.construct(NativeJavaClass.java:193)
at org.mozilla.javascript.ScriptRuntime.newObject(ScriptRuntime.java:2267)
at JS$module$yuicompressor$js$25._c1(module yuicompressor.js:66)
at JS$module$yuicompressor$js$25.call(module yuicompressor.js)
at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
at JS$module$faststatic$js$23._c26(module faststatic.js:317)
at JS$module$faststatic$js$23.call(module faststatic.js)
at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
at JS$module$faststatic$js$23._c27(module faststatic.js:325)
at JS$module$faststatic$js$23.call(module faststatic.js)
at org.mozilla.javascript.NativeArray.iterativeMethod(NativeArray.java:1565)
at org.mozilla.javascript.NativeArray.execIdCall(NativeArray.java:313)
at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:127)
at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
at JS$module$faststatic$js$23._c25(module faststatic.js:324)
at JS$module$faststatic$js$23.call(module faststatic.js)
at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
at JS$module$faststatic$js$23._c21(module faststatic.js:302)
at JS$module$faststatic$js$23.call(module faststatic.js)
at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:86)
at JS$module$etherpad$helpers$js$22._c24(module etherpad/helpers.js:171)
at JS$module$etherpad$helpers$js$22.call(module etherpad/helpers.js)
at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:119)
at JS$html$ejs$242._c1(html.ejs:33)
at JS$html$ejs$242.call(html.ejs)
at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2348)
at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:272)
at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:127)
at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:86)
at JS$module$ejs$js$11._c22(module ejs.js:395)
at JS$module$ejs$js$11.call(module ejs.js)
at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
at JS$module$etherpad$utils$js$30._c14(module etherpad/utils.js:174)
at JS$module$etherpad$utils$js$30.call(module etherpad/utils.js)
at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
at JS$module$etherpad$utils$js$30._c16(module etherpad/utils.js:187)
at JS$module$etherpad$utils$js$30.call(module etherpad/utils.js)
at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
at JS$module$etherpad$utils$js$30._c17(module etherpad/utils.js:206)
at JS$module$etherpad$utils$js$30.call(module etherpad/utils.js)
at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
at JS$module$etherpad$utils$js$30._c19(module etherpad/utils.js:219)
at JS$module$etherpad$utils$js$30.call(module etherpad/utils.js)
at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
at JS$module$etherpad$utils$js$30._c25(module etherpad/utils.js:257)
at JS$module$etherpad$utils$js$30.call(module etherpad/utils.js)
at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
at JS$module$main$js$8._c6(module main.js:134)
at JS$module$main$js$8.call(module main.js)
at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
at JS$module$onerror$js$263._c0(module onerror.js:24)
at JS$module$onerror$js$263.call(module onerror.js)
at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:401)
at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3004)
at JS$module$onerror$js$263.call(module onerror.js)
at JS$module$onerror$js$263.exec(module onerror.js)
at net.appjet.bodylock.InnerExecutable$$anonfun$execute$1.apply(bodylock.scala:76)
at net.appjet.bodylock.InnerExecutable$$anonfun$execute$1.apply(bodylock.scala:75)
at net.appjet.bodylock.BodyLock$.runInContext(bodylock.scala:111)
at net.appjet.bodylock.InnerExecutable.execute(bodylock.scala:75)
... 23 more
Caused by:
net.appjet.bodylock.JSRuntimeException: Error: yuicompressor.compressJS error: 1:7:syntax error
at net.appjet.bodylock.BodyLock$.unwrapExceptionIfNecessary(bodylock.scala:160)
at net.appjet.bodylock.InnerExecutable.execute(bodylock.scala:80)
at net.appjet.oui.execution$$anonfun$execute$4.apply(execution.scala:508)
at net.appjet.oui.NoninheritedDynamicVariable.withValue(dynamicvar.scala:38)
at net.appjet.oui.ExecutionContextUtils$.withContext(execution.scala:334)
at net.appjet.oui.execution$.execute(execution.scala:504)
at net.appjet.oui.execution$.execute(execution.scala:483)
at net.appjet.oui.OuiServlet.execute(execution.scala:413)
at net.appjet.oui.OuiServlet.doGet(execution.scala:360)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:502)
at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
at org.mortbay.jetty.handler.HandlerList.handle(HandlerList.java:49)
at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
at org.mortbay.jetty.Server.handle(Server.java:326)
at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:536)
at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:913)
at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:539)
at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:405)
at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
Caused by: org.mozilla.javascript.JavaScriptException: [object Error](module yuicompressor.js#55)
at JS$module$yuicompressor$js$25._c6(module yuicompressor.js:55)
at JS$module$yuicompressor$js$25.call(module yuicompressor.js)
at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
at JS$module$yuicompressor$js$25._c4(module yuicompressor.js:45)
at JS$module$yuicompressor$js$25.call(module yuicompressor.js)
at org.mozilla.javascript.JavaAdapter.doCall(JavaAdapter.java:568)
at org.mozilla.javascript.JavaAdapter.callMethod(JavaAdapter.java:543)
at adapter5.error()
at yuicompressor.org.mozilla.javascript.Parser.addError(Parser.java:140)
at yuicompressor.org.mozilla.javascript.Parser.reportError(Parser.java:154)
at yuicompressor.org.mozilla.javascript.Parser.primaryExpr(Parser.java:2132)
at yuicompressor.org.mozilla.javascript.Parser.memberExpr(Parser.java:1740)
at yuicompressor.org.mozilla.javascript.Parser.unaryExpr(Parser.java:1601)
at yuicompressor.org.mozilla.javascript.Parser.mulExpr(Parser.java:1530)
at yuicompressor.org.mozilla.javascript.Parser.addExpr(Parser.java:1511)
at yuicompressor.org.mozilla.javascript.Parser.shiftExpr(Parser.java:1491)
at yuicompressor.org.mozilla.javascript.Parser.relExpr(Parser.java:1465)
at yuicompressor.org.mozilla.javascript.Parser.eqExpr(Parser.java:1421)
at yuicompressor.org.mozilla.javascript.Parser.bitAndExpr(Parser.java:1410)
at yuicompressor.org.mozilla.javascript.Parser.bitXorExpr(Parser.java:1399)
at yuicompressor.org.mozilla.javascript.Parser.bitOrExpr(Parser.java:1388)
at yuicompressor.org.mozilla.javascript.Parser.andExpr(Parser.java:1376)
at yuicompressor.org.mozilla.javascript.Parser.orExpr(Parser.java:1364)
at yuicompressor.org.mozilla.javascript.Parser.condExpr(Parser.java:1347)
at yuicompressor.org.mozilla.javascript.Parser.assignExpr(Parser.java:1332)
at yuicompressor.org.mozilla.javascript.Parser.expr(Parser.java:1319)
at yuicompressor.org.mozilla.javascript.Parser.statementHelper(Parser.java:1216)
at yuicompressor.org.mozilla.javascript.Parser.statement(Parser.java:666)
at yuicompressor.org.mozilla.javascript.Parser.parse(Parser.java:388)
at yuicompressor.org.mozilla.javascript.Parser.parse(Parser.java:347)
at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:312)
at com.yahoo.platform.yui.compressor.JavaScriptCompressor.(JavaScriptCompressor.java:535)
at sun.reflect.GeneratedConstructorAccessor19.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
at org.mozilla.javascript.MemberBox.newInstance(MemberBox.java:184)
at org.mozilla.javascript.NativeJavaClass.constructSpecific(NativeJavaClass.java:274)
at org.mozilla.javascript.NativeJavaClass.construct(NativeJavaClass.java:193)
at org.mozilla.javascript.ScriptRuntime.newObject(ScriptRuntime.java:2267)
at JS$module$yuicompressor$js$25._c1(module yuicompressor.js:66)
at JS$module$yuicompressor$js$25.call(module yuicompressor.js)
at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
at JS$module$faststatic$js$23._c26(module faststatic.js:317)
at JS$module$faststatic$js$23.call(module faststatic.js)
at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
at JS$module$faststatic$js$23._c27(module faststatic.js:325)
at JS$module$faststatic$js$23.call(module faststatic.js)
at org.mozilla.javascript.NativeArray.iterativeMethod(NativeArray.java:1565)
at org.mozilla.javascript.NativeArray.execIdCall(NativeArray.java:313)
at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:127)
at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
at JS$module$faststatic$js$23._c25(module faststatic.js:324)
at JS$module$faststatic$js$23.call(module faststatic.js)
at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
at JS$module$faststatic$js$23._c21(module faststatic.js:302)
at JS$module$faststatic$js$23.call(module faststatic.js)
at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:86)
at JS$module$etherpad$helpers$js$22._c24(module etherpad/helpers.js:171)
at JS$module$etherpad$helpers$js$22.call(module etherpad/helpers.js)
at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:119)
at JS$html$ejs$242._c1(html.ejs:33)
at JS$html$ejs$242.call(html.ejs)
at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2348)
at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:272)
at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:127)
at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:86)
at JS$module$ejs$js$11._c22(module ejs.js:395)
at JS$module$ejs$js$11.call(module ejs.js)
at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
at JS$module$etherpad$utils$js$30._c14(module etherpad/utils.js:174)
at JS$module$etherpad$utils$js$30.call(module etherpad/utils.js)
at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
at JS$module$etherpad$utils$js$30._c16(module etherpad/utils.js:187)
at JS$module$etherpad$utils$js$30.call(module etherpad/utils.js)
at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
at JS$module$etherpad$control$admincontrol$js$78._c5(module etherpad/control/admincontrol.js:134)
at JS$module$etherpad$control$admincontrol$js$78.call(module etherpad/control/admincontrol.js)
at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:57)
at JS$module$dispatch$js$9._c11(module dispatch.js:136)
at JS$module$dispatch$js$9.call(module dispatch.js)
at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2348)
at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:272)
at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:127)
at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)
at JS$module$dispatch$js$9._c9(module dispatch.js:96)
at JS$module$dispatch$js$9.call(module dispatch.js)
at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:119)
at JS$module$main$js$8._c24(module main.js:423)
at JS$module$main$js$8.call(module main.js)
at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:108)
at JS$module$main$js$8._c5(module main.js:123)
at JS$module$main$js$8.call(module main.js)
at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:119)
at JS$module$onrequest$js$236._c0(module onrequest.js:24)
at JS$module$onrequest$js$236.call(module onrequest.js)
at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:401)
at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3004)
at JS$module$onrequest$js$236.call(module onrequest.js)
at JS$module$onrequest$js$236.exec(module onrequest.js)
at net.appjet.bodylock.InnerExecutable$$anonfun$execute$1.apply(bodylock.scala:76)
at net.appjet.bodylock.InnerExecutable$$anonfun$execute$1.apply(bodylock.scala:75)
at net.appjet.bodylock.BodyLock$.runInContext(bodylock.scala:111)
at net.appjet.bodylock.InnerExecutable.execute(bodylock.scala:75)
... 23 more

**Comment by sesam** [comment]
The top row of the error is  yuicompressor.compressJS  which presumably bakes together all clientside javascript to create a tiny script download. Something in the packaged version doesn't deal well with that.

''My suggestion is to get the source from here, using git the get the freshest version.''

**Comment by zeigerpuppy** [comment]
ok, this is starting to look like a dependency issue, if I install the "search" plugin before "padHierarchy" there is no error.  Looks like a  dependency check is needed.  
... woops, spoke too soon, reloading and it is broken again.
but i think I found a way to roll back (need to do both):

http://domain:9000/ep/admin/pluginmanager/?plugin=padHierarchy&action=uninstall
http://domain.net:9000/ep/admin/pluginmanager/?plugin=search&action=uninstall

although, this is still weird, I now have 2 "home" buttons on the right and I get a new one everytime I do the install/uninstall plugin dance!

**Comment by zeigerpuppy** [comment]
when I have enabled search plugins. I get an error on the right saying:
404 not found: /ep/pad/view/ro.3PfHCD0ApLc/latest

not sure, maybe this should correspond to the search index?
searching appears broken

**Comment by sesam** [comment]
This is not a support forum. Please make one ticket per issue, and search for issues to avoid making duplicates.
I suggest you ask on the google group / maillist instead. To get help from me or a developer, you'll have to try installing the development version.
(Your "Error on the right" is a common question on the maillist. Go to your confing under etc/ and remove/change the row for motd)

**Comment by zeigerpuppy** [comment]
Sorry for the extra verbosity, 
To clarify, the errors are from the current development version, pulled from git and then built as a package.  I'll follow up on the mailing list, thanks
