### ISSUE TITLE
Broken Timeline and read-only-view after fixing some issues

### ISSUE THREAD

**Issue by df-uk** [ether/pad#253]
Hi everybody,

i got my etherpad from etherpad.org repository on a ubuntu server.

Timeline and read-only-view was working fine, but after (succsesfully) fixing some issues (import/Export, "Undefined" in email-invitation, some Pad-Inspector related issues "snoop", "head" etc) suddenly the timeline and the read-only-view quit working - unfortunatly i cant say at which point of issue-fixing...:

If you click at timeline or use the read-only-url it says:

"Oops! A server error occured. It's been logged." - the created URL seems to be correct - both in timeline- and readonly view.

The Admin-Exceptions Monitor tells me:

net.appjet.bodylock.JSRuntimeException: Error while executing: TypeError: Cannot read property "fullName" from undefined (module etherpad/pad/padusers.js#111)
        at net.appjet.bodylock.InnerExecutable.execute(bodylock.scala:84)
        at net.appjet.oui.execution$$anonfun$execute$4.apply(execution.scala:508)
        at net.appjet.oui.NoninheritedDynamicVariable.withValue(dynamicvar.scala:38)
        at net.appjet.oui.ExecutionContextUtils$.withContext(execution.scala:334)
        at net.appjet.oui.execution$.execute(execution.scala:504)
        at net.appjet.oui.execution$.execute(execution.scala:483)
        at net.appjet.oui.OuiServlet.execute(execution.scala:413)
        at net.appjet.oui.OuiServlet.doGet(execution.scala:360)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:502)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.handler.HandlerList.handle(HandlerList.java:49)
        at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:536)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:913)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:539)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:405)
        at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
        at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
Caused by: org.mozilla.javascript.EcmaError: TypeError: Cannot read property "fullName" from undefined (module etherpad/pad/padusers.js#111)
        at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3559)
        at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3537)
        at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3565)
        at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:3584)
        at org.mozilla.javascript.ScriptRuntime.undefReadError(ScriptRuntime.java:3597)
        at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1381)
        at JS$module$etherpad$pad$padusers$js$58._c8(module etherpad/pad/padusers.js:111)
        at JS$module$etherpad$pad$padusers$js$58.call(module etherpad/pad/padusers.js)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
        at JS$module$etherpad$collab$collab$server$js$34._c29(module etherpad/collab/collab_server.js:344)
        at JS$module$etherpad$collab$collab$server$js$34.call(module etherpad/collab/collab_server.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
        at JS$module$etherpad$collab$collab$server$js$34._c33(module etherpad/collab/collab_server.js:370)
        at JS$module$etherpad$collab$collab$server$js$34.call(module etherpad/collab/collab_server.js)
        at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)
        at JS$module$etherpad$collab$ace$easysync2$js$35._c6(module etherpad/collab/ace/easysync2.js:66)
        at JS$module$etherpad$collab$ace$easysync2$js$35.call(module etherpad/collab/ace/easysync2.js)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
        at JS$module$etherpad$collab$collab$server$js$34._c32(module etherpad/collab/collab_server.js:367)
        at JS$module$etherpad$collab$collab$server$js$34.call(module etherpad/collab/collab_server.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
        at JS$module$etherpad$control$pad$pad$view$control$js$148._c9(module etherpad/control/pad/pad_view_control.js:147)
        at JS$module$etherpad$control$pad$pad$view$control$js$148.call(module etherpad/control/pad/pad_view_control.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
        at JS$module$etherpad$pad$padutils$js$18._c8(module etherpad/pad/padutils.js:86)
        at JS$module$etherpad$pad$padutils$js$18.call(module etherpad/pad/padutils.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
        at JS$module$etherpad$pad$model$js$37._c7(module etherpad/pad/model.js:459)
        at JS$module$etherpad$pad$model$js$37.call(module etherpad/pad/model.js)
        at org.mozilla.javascript.JavaAdapter.doCall(JavaAdapter.java:568)
        at org.mozilla.javascript.JavaAdapter.callMethod(JavaAdapter.java:543)
        at adapter2.apply(<adapter>)
        at net.appjet.ajstdlib.SQLBase$$anonfun$inTransaction$1$$anonfun$apply$1.apply(sqlbase.scala:114)
        at net.appjet.oui.NoninheritedDynamicVariable.withValue(dynamicvar.scala:38)
        at net.appjet.ajstdlib.SQLBase$$anonfun$inTransaction$1.apply(sqlbase.scala:109)
        at net.appjet.ajstdlib.SQLBase$$anonfun$inTransaction$1.apply(sqlbase.scala:105)
        at net.appjet.ajstdlib.SQLBase$$anonfun$withConnection$1.apply(sqlbase.scala:93)
        at net.appjet.oui.NoninheritedDynamicVariable.withValue(dynamicvar.scala:38)
        at net.appjet.ajstdlib.SQLBase.withConnection(sqlbase.scala:92)
        at net.appjet.ajstdlib.SQLBase.inTransaction(sqlbase.scala:105)
        at sun.reflect.GeneratedMethodAccessor76.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:160)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:243)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
        at JS$module$sqlbase$sqlcommon$js$16._c6(module sqlbase/sqlcommon.js:64)
        at JS$module$sqlbase$sqlcommon$js$16.call(module sqlbase/sqlcommon.js)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
        at JS$module$etherpad$pad$model$js$37._c6(module etherpad/pad/model.js:107)
        at JS$module$etherpad$pad$model$js$37.call(module etherpad/pad/model.js)
        at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:57)
        at JS$module$sync$js$15._c7(module sync.js:75)
        at JS$module$sync$js$15.call(module sync.js)
        at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)
        at JS$module$etherpad$pad$model$js$37._c47(module etherpad/pad/model.js:483)
        at JS$module$etherpad$pad$model$js$37.call(module etherpad/pad/model.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
        at JS$module$etherpad$pad$model$js$37._c5(module etherpad/pad/model.js:106)
        at JS$module$etherpad$pad$model$js$37.call(module etherpad/pad/model.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:86)
        at JS$module$etherpad$pad$padutils$js$18._c7(module etherpad/pad/padutils.js:88)
        at JS$module$etherpad$pad$padutils$js$18.call(module etherpad/pad/padutils.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:86)
        at JS$module$etherpad$control$pad$pad$view$control$js$148._c1(module etherpad/control/pad/pad_view_control.js:146)
        at JS$module$etherpad$control$pad$pad$view$control$js$148.call(module etherpad/control/pad/pad_view_control.js)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
        at JS$module$dispatch$js$9._c11(module dispatch.js:123)
        at JS$module$dispatch$js$9.call(module dispatch.js)
        at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2348)
        at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:272)
        at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:127)
        at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)
        at JS$module$dispatch$js$9._c9(module dispatch.js:96)
        at JS$module$dispatch$js$9.call(module dispatch.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:119)
        at JS$module$etherpad$control$pad$pad$control$js$146._c2(module etherpad/control/pad/pad_control.js:91)
        at JS$module$etherpad$control$pad$pad$control$js$146.call(module etherpad/control/pad/pad_control.js)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
        at JS$module$dispatch$js$9._c11(module dispatch.js:123)
        at JS$module$dispatch$js$9.call(module dispatch.js)
        at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2348)
        at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:272)
        at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:127)
        at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)
        at JS$module$dispatch$js$9._c9(module dispatch.js:96)
        at JS$module$dispatch$js$9.call(module dispatch.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:119)
        at JS$module$main$js$8._c24(module main.js:412)
        at JS$module$main$js$8.call(module main.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:108)
        at JS$module$main$js$8._c5(module main.js:123)
        at JS$module$main$js$8.call(module main.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:119)
        at JS$module$onrequest$js$236._c0(module onrequest.js:24)
        at JS$module$onrequest$js$236.call(module onrequest.js)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:401)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3004)
        at JS$module$onrequest$js$236.call(module onrequest.js)
        at JS$module$onrequest$js$236.exec(module onrequest.js)
        at net.appjet.bodylock.InnerExecutable$$anonfun$execute$1.apply(bodylock.scala:76)
        at net.appjet.bodylock.InnerExecutable$$anonfun$execute$1.apply(bodylock.scala:75)
        at net.appjet.bodylock.BodyLock$.runInContext(bodylock.scala:111)
        at net.appjet.bodylock.InnerExecutable.execute(bodylock.scala:75)
        ... 23 more

Anybody got an idea what is going (wr)on(g)  there?

Thank you in advance!

df-uk

**Comment by sesam** [comment]
:) Could you make a code diff between the code from the repo and the code with your fixes? Chances are you'll see some simple spelling error or similar immediately. Otherwise post it here and cross your fingers. Google is your friend if you need help with "git diff" etc.

**Comment by redhog** [comment]
Hey, even better:

I guess you did git clone to get a copy of the code, so you have a .git subdirectory in your source code directory? If so, on github, fork the same repo you cloned using the "fork" button, and then set that repo as your remote repo for your clone (git remote add), and push to it. That way, we'll be able to see what you've changed and maybe get a clue as to why it doesn't work :) If you need help w git, please feel free to drop me a mail / organize a time to meet on chat (at #etherpad on irc.freenode.net)

**Comment by sesam** [comment]
Hey, let's get this issue moving.
Here's another option; send me the source code with your changes included and I'll try to get the fixes into the official version. Then you can archive your broken version and make a fresh install.
Sounds tempting?
